# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

exporters:
  logging:
  otlp/teletrace:
    endpoint: teletrace:4317
    tls:
      insecure: true

service:
  pipelines:
    traces/teletrace:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/teletrace]
